import { Recipe } from './types';

export const formatNumber = (num: number): string => {
  const rounded = Math.round(num * 100) / 100;
  const decimalPart = rounded % 1;
  const intPart = Math.floor(rounded);
  
  if (Math.abs(decimalPart - 0.33) < 0.05) return intPart ? `${intPart} ⅓` : '⅓';
  if (Math.abs(decimalPart - 0.66) < 0.05) return intPart ? `${intPart} ⅔` : '⅔';
  if (Math.abs(decimalPart - 0.25) < 0.05) return intPart ? `${intPart} ¼` : '¼';
  if (Math.abs(decimalPart - 0.5) < 0.05) return intPart ? `${intPart} ½` : '½';
  if (Math.abs(decimalPart - 0.75) < 0.05) return intPart ? `${intPart} ¾` : '¾';
  
  return rounded.toString();
};

export const scaleAmount = (amountStr: string, base: number, target: number): string => {
  if (!base || base === target) return amountStr;
  
  const factor = target / base;
  const regex = /^(\d+[\s-]+\d+\/\d+|\d+\/\d+|\d+(?:\.\d+)?)\s*(.*)$/;
  const match = amountStr.match(regex);
  
  if (!match) return amountStr;
  
  let numStr = match[1];
  const unitStr = match[2];
  let value = 0;
  
  if (numStr.includes('/')) {
     if (numStr.includes(' ') || numStr.includes('-')) {
        const parts = numStr.split(/[\s-]+/);
        const frac = parts[1].split('/');
        value = parseInt(parts[0]) + parseInt(frac[0]) / parseInt(frac[1]);
     } else {
        const frac = numStr.split('/');
        value = parseInt(frac[0]) / parseInt(frac[1]);
     }
  } else {
     value = parseFloat(numStr);
  }
  
  if (isNaN(value)) return amountStr;
  
  const newValue = value * factor;
  // Preserve space if unit exists, else no space
  return `${formatNumber(newValue)}${unitStr ? ' ' + unitStr : ''}`;
};

export const generateShareText = (recipe: Recipe, currentServings?: number): string => {
   const servings = currentServings || recipe.servings || 2;
   const ingredientsList = recipe.ingredients.map(i => {
       const amount = scaleAmount(i.amount, recipe.servings || 2, servings);
       return `• ${amount} ${i.name}`;
   }).join('\n');

   let nutritionText = "";
   if (recipe.nutrition) {
      nutritionText = `\n📊 Nutrition: Protein ${recipe.nutrition.protein} | Carbs ${recipe.nutrition.carbs} | Fat ${recipe.nutrition.fat} | Fiber ${recipe.nutrition.fiber}`;
   }
   
   if (recipe.drinkPairing) {
       nutritionText += `\n🍷 Pairing: ${recipe.drinkPairing}`;
   }

   return `🍳 ${recipe.name}
${recipe.description}

🔥 ${recipe.calories} | 🕒 ${parseInt(recipe.prepTime) + parseInt(recipe.cookTime)}m | ⚡ ${recipe.difficulty} | 👥 ${servings} Servings${nutritionText}

🛒 Ingredients:
${ingredientsList}

👨‍🍳 Instructions:
${recipe.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Generated by ChefGenie 🧞‍♂️`;
};

export const shareRecipe = async (text: string, title: string, onCopy?: () => void) => {
    if (navigator.share) {
        try {
            await navigator.share({
                title: title,
                text: text
            });
        } catch (err) {
            console.log("Share skipped or failed", err);
        }
    } else {
        try {
            await navigator.clipboard.writeText(text);
            if (onCopy) onCopy();
        } catch (err) {
            console.error("Clipboard failed", err);
        }
    }
}